### ISSUE TITLE
How to add onItemClickListener ?

### ISSUE THREAD

**Issue by MohamedAliArafa** [mhmtsdtkrt/NeverEmptyListView#2]
i can't find on item click listener only on holder clock listener

**Comment by mskurt** [comment]
Hello,
Let me give some information about NeverEmptyListView. This custom view do not extend a ListView. It contains a ListView. Follow below code to solve your problem. It is also written on 6th instruction of README.md.

```
 neverEmptyListView.getListview().setOnItemClickListener(new AdapterView.OnItemClickListener() {
     @Override
     public void onItemClick(AdapterView<?> parent, View view, int position, long id) {

     }
 });
```

**Comment by MohamedAliArafa** [comment]
Hello Mr Skurt
Thank you for your fast replay and the great NeverEmptyListView , it is really cool and i was looking for one like it for a long time so i'm really appreciated for your work mr skurt 

Your tip is helpful sorry that i didn't notice it at first .

Best Regards ,

Your sincerely
Mohamed Arafa

**Comment by mskurt** [comment]
You're welcome Mr. Arafa. 
I thank you for your appreciations. If you have any issue, let me know please.

Best Regards.
